### ISSUE TITLE
can this also work with CP web gateway ? 

### ISSUE THREAD

**Issue by sachinbhutani** [gofinance/ib#40]
can this work with CP web gateway ? 
https://interactivebrokers.github.io/cpwebapi/index.html#login
if basic functions can work, I can work on additional functions required for CP Web gateway.

**Comment by dsouzae** [comment]
Hello, 

This project only supports the IB TWS API (at the moment).

Support for REST API and Websockets via the CP Web Gateway would most likely need to be covered by a separate project

A compatible API as `gofinance/ib` could be rewritten using the CP Web Gateway (I haven't checked if there are equivalent methods in the REST API).  It would take someone a lot of time to implement and test, but it would eliminate the need for the complicated setup for CI testing.
